spring:
  application:
    name: bankaccount


  datasource:
    url: jdbc:mysql://localhost:3306/bankaccount
    username: root
    password: Baku2018
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080